// Trace reporter — generates single-file HTML reports from trace data
//
// The generated HTML embeds all CSS/JS inline and base64-encodes screenshots,
// producing a self-contained file that can be opened in any browser.

use std::fs;

use super::recorder::{TraceData, TraceSummary};
use super::store;

/// Generate an HTML report for a trace and save it to the trace directory.
/// Returns the path to the generated HTML file.
pub fn generate_report(trace: &TraceData) -> Result<String, String> {
    let html = render_html(trace);
    let dir = store::trace_dir(&trace.trace_id);
    let path = dir.join("report.html");

    fs::write(&path, &html)
        .map_err(|e| format!("Failed to write report: {}", e))?;

    Ok(path.to_string_lossy().to_string())
}

/// Render the complete HTML report as a string
fn render_html(trace: &TraceData) -> String {
    let status = if trace.ended_at.is_some() {
        "Completed"
    } else {
        "In Progress"
    };

    let status_class = if trace.ended_at.is_some() {
        "completed"
    } else {
        "in-progress"
    };

    let summary_html = render_summary(&trace.summary);
    let steps_html = render_steps(trace);

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Era Trace: {name}</title>
<style>
{css}
</style>
</head>
<body>
<header>
  <div class="header-content">
    <h1>Era Trace Report</h1>
    <div class="trace-meta">
      <span class="trace-id">{trace_id}</span>
      <span class="status {status_class}">{status}</span>
    </div>
  </div>
</header>

<main>
  <section class="info-panel">
    <div class="info-grid">
      <div class="info-item">
        <label>Name</label>
        <value>{name}</value>
      </div>
      <div class="info-item">
        <label>Started</label>
        <value>{started_at}</value>
      </div>
      <div class="info-item">
        <label>Ended</label>
        <value>{ended_at}</value>
      </div>
      {device_html}
    </div>
  </section>

  {summary_html}

  <section class="timeline">
    <h2>Steps Timeline</h2>
    {steps_html}
  </section>
</main>

<footer>
  <p>Generated by <strong>Era</strong> — iOS Simulator CLI</p>
</footer>

<script>
{js}
</script>
</body>
</html>"#,
        name = html_escape(&trace.name),
        trace_id = html_escape(&trace.trace_id),
        status = status,
        status_class = status_class,
        started_at = html_escape(&trace.started_at),
        ended_at = trace
            .ended_at
            .as_deref()
            .unwrap_or("—"),
        device_html = render_device(trace),
        summary_html = summary_html,
        steps_html = steps_html,
        css = CSS,
        js = JS,
    )
}

fn render_device(trace: &TraceData) -> String {
    match &trace.device {
        Some(dev) => {
            let runtime = dev
                .runtime
                .as_deref()
                .unwrap_or("Unknown");
            let scale = dev
                .scale
                .map(|s| format!("{}x", s))
                .unwrap_or_else(|| "—".to_string());
            format!(
                r#"<div class="info-item">
        <label>Device</label>
        <value>{name}</value>
      </div>
      <div class="info-item">
        <label>UDID</label>
        <value class="mono">{udid}</value>
      </div>
      <div class="info-item">
        <label>Runtime</label>
        <value>{runtime}</value>
      </div>
      <div class="info-item">
        <label>Scale</label>
        <value>{scale}</value>
      </div>"#,
                name = html_escape(&dev.name),
                udid = html_escape(&dev.udid),
                runtime = html_escape(runtime),
                scale = scale,
            )
        }
        None => String::new(),
    }
}

fn render_summary(summary: &Option<TraceSummary>) -> String {
    match summary {
        Some(s) => {
            let pass_rate = if s.assertions.total > 0 {
                format!(
                    "{:.0}%",
                    (s.assertions.passed as f64 / s.assertions.total as f64) * 100.0
                )
            } else {
                "N/A".to_string()
            };

            let duration = format_duration(s.total_duration_ms);

            format!(
                r#"<section class="summary">
    <h2>Summary</h2>
    <div class="summary-grid">
      <div class="summary-card">
        <div class="card-value">{steps}</div>
        <div class="card-label">Total Steps</div>
      </div>
      <div class="summary-card">
        <div class="card-value">{duration}</div>
        <div class="card-label">Total Duration</div>
      </div>
      <div class="summary-card {assert_class}">
        <div class="card-value">{passed}/{total}</div>
        <div class="card-label">Assertions ({pass_rate})</div>
      </div>
      <div class="summary-card">
        <div class="card-value">{retries}</div>
        <div class="card-label">Retries</div>
      </div>
    </div>
  </section>"#,
                steps = s.total_steps,
                duration = duration,
                passed = s.assertions.passed,
                total = s.assertions.total,
                pass_rate = pass_rate,
                retries = s.retries,
                assert_class = if s.assertions.failed > 0 {
                    "has-failures"
                } else {
                    "all-passed"
                },
            )
        }
        None => String::new(),
    }
}

fn render_steps(trace: &TraceData) -> String {
    if trace.steps.is_empty() {
        return "<p class=\"empty\">No steps recorded.</p>".to_string();
    }

    let mut html = String::new();
    for step in &trace.steps {
        let action_class = match step.action.as_str() {
            "assert" => {
                if step
                    .output
                    .get("pass")
                    .and_then(|v| v.as_bool())
                    .unwrap_or(false)
                {
                    "action-assert-pass"
                } else {
                    "action-assert-fail"
                }
            }
            "tap" | "tap-region" => "action-tap",
            "fill" => "action-fill",
            "swipe" => "action-swipe",
            "snapshot" => "action-snapshot",
            "screenshot" => "action-screenshot",
            _ => "action-other",
        };

        let input_json = serde_json::to_string_pretty(&step.input).unwrap_or_default();
        let output_json = serde_json::to_string_pretty(&step.output).unwrap_or_default();

        let screenshot_before = render_screenshot(&step.screenshot_before, &trace.trace_id);
        let screenshot_after = render_screenshot(&step.screenshot_after, &trace.trace_id);

        html.push_str(&format!(
            r#"<div class="step {action_class}" data-seq="{seq}">
      <div class="step-header" onclick="toggleStep(this)">
        <span class="step-seq">#{seq}</span>
        <span class="step-action">{action}</span>
        <span class="step-duration">{duration}ms</span>
        <span class="step-time">{timestamp}</span>
        <span class="step-toggle">▸</span>
      </div>
      <div class="step-body" style="display:none">
        <div class="step-data">
          <div class="data-panel">
            <h4>Input</h4>
            <pre><code>{input}</code></pre>
          </div>
          <div class="data-panel">
            <h4>Output</h4>
            <pre><code>{output}</code></pre>
          </div>
        </div>
        {screenshot_before}
        {screenshot_after}
      </div>
    </div>
"#,
            action_class = action_class,
            seq = step.seq,
            action = html_escape(&step.action),
            duration = step.duration_ms,
            timestamp = html_escape(&step.timestamp),
            input = html_escape(&input_json),
            output = html_escape(&output_json),
            screenshot_before = screenshot_before,
            screenshot_after = screenshot_after,
        ));
    }
    html
}

fn render_screenshot(path: &Option<String>, trace_id: &str) -> String {
    match path {
        Some(filename) => {
            let full_path = store::trace_dir(trace_id).join(filename);
            match fs::read(&full_path) {
                Ok(bytes) => {
                    use base64::Engine;
                    let b64 = base64::engine::general_purpose::STANDARD.encode(&bytes);
                    let ext = full_path
                        .extension()
                        .and_then(|e| e.to_str())
                        .unwrap_or("png");
                    format!(
                        r#"<div class="screenshot">
          <img src="data:image/{ext};base64,{b64}" alt="{filename}" loading="lazy">
          <span class="screenshot-label">{filename}</span>
        </div>"#,
                        ext = ext,
                        b64 = b64,
                        filename = html_escape(filename),
                    )
                }
                Err(_) => {
                    format!(
                        r#"<div class="screenshot missing">
          <span>Screenshot not found: {}</span>
        </div>"#,
                        html_escape(filename)
                    )
                }
            }
        }
        None => String::new(),
    }
}

fn format_duration(ms: u64) -> String {
    if ms < 1000 {
        format!("{}ms", ms)
    } else if ms < 60_000 {
        format!("{:.1}s", ms as f64 / 1000.0)
    } else {
        let mins = ms / 60_000;
        let secs = (ms % 60_000) / 1000;
        format!("{}m {}s", mins, secs)
    }
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#x27;")
}

// ---------------------------------------------------------------------------
// Embedded CSS (dark theme)
// ---------------------------------------------------------------------------

const CSS: &str = r#"
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  background: #1a1a2e;
  color: #e0e0e0;
  line-height: 1.6;
}
header {
  background: #16213e;
  border-bottom: 2px solid #0f3460;
  padding: 1.5rem 2rem;
}
.header-content { max-width: 1200px; margin: 0 auto; }
h1 { color: #53d8fb; font-size: 1.5rem; margin-bottom: 0.5rem; }
.trace-meta { display: flex; gap: 1rem; align-items: center; }
.trace-id { font-family: monospace; color: #8892b0; font-size: 0.9rem; }
.status {
  padding: 0.2rem 0.8rem; border-radius: 12px;
  font-size: 0.8rem; font-weight: 600; text-transform: uppercase;
}
.status.completed { background: #1b4332; color: #95d5b2; }
.status.in-progress { background: #462a00; color: #ffd166; }
main { max-width: 1200px; margin: 2rem auto; padding: 0 2rem; }
h2 { color: #53d8fb; margin-bottom: 1rem; font-size: 1.2rem; }
.info-panel {
  background: #16213e; border-radius: 8px;
  padding: 1.5rem; margin-bottom: 2rem;
}
.info-grid {
  display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 1rem;
}
.info-item label {
  display: block; color: #8892b0; font-size: 0.75rem;
  text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.25rem;
}
.info-item value { display: block; font-size: 0.95rem; }
.info-item .mono { font-family: monospace; font-size: 0.85rem; word-break: break-all; }
.summary { margin-bottom: 2rem; }
.summary-grid {
  display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
  gap: 1rem;
}
.summary-card {
  background: #16213e; border-radius: 8px; padding: 1.25rem;
  text-align: center; border: 1px solid #0f3460;
}
.summary-card.has-failures { border-color: #e63946; }
.summary-card.all-passed { border-color: #2d6a4f; }
.card-value { font-size: 1.8rem; font-weight: 700; color: #53d8fb; }
.has-failures .card-value { color: #e63946; }
.all-passed .card-value { color: #95d5b2; }
.card-label { color: #8892b0; font-size: 0.8rem; margin-top: 0.25rem; }
.timeline { margin-bottom: 2rem; }
.step {
  background: #16213e; border-radius: 8px; margin-bottom: 0.5rem;
  border-left: 3px solid #0f3460; overflow: hidden;
}
.step.action-tap { border-left-color: #53d8fb; }
.step.action-fill { border-left-color: #a78bfa; }
.step.action-swipe { border-left-color: #ffd166; }
.step.action-snapshot { border-left-color: #8892b0; }
.step.action-screenshot { border-left-color: #8892b0; }
.step.action-assert-pass { border-left-color: #95d5b2; }
.step.action-assert-fail { border-left-color: #e63946; }
.step-header {
  display: flex; align-items: center; gap: 1rem;
  padding: 0.75rem 1rem; cursor: pointer; user-select: none;
}
.step-header:hover { background: rgba(255,255,255,0.03); }
.step-seq { color: #8892b0; font-family: monospace; min-width: 3rem; }
.step-action {
  font-weight: 600; text-transform: uppercase; font-size: 0.85rem;
  min-width: 6rem;
}
.action-tap .step-action { color: #53d8fb; }
.action-fill .step-action { color: #a78bfa; }
.action-swipe .step-action { color: #ffd166; }
.action-snapshot .step-action { color: #8892b0; }
.action-assert-pass .step-action { color: #95d5b2; }
.action-assert-fail .step-action { color: #e63946; }
.step-duration { color: #8892b0; font-size: 0.85rem; font-family: monospace; }
.step-time { color: #555; font-size: 0.8rem; margin-left: auto; font-family: monospace; }
.step-toggle { color: #8892b0; transition: transform 0.2s; }
.step-header.open .step-toggle { transform: rotate(90deg); }
.step-body { padding: 0 1rem 1rem; }
.step-data { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
.data-panel h4 { color: #8892b0; font-size: 0.75rem; text-transform: uppercase; margin-bottom: 0.5rem; }
.data-panel pre {
  background: #0d1117; border-radius: 6px; padding: 0.75rem;
  overflow-x: auto; font-size: 0.8rem; line-height: 1.5;
}
.data-panel code { color: #c9d1d9; }
.screenshot { margin-top: 1rem; }
.screenshot img { max-width: 100%; max-height: 400px; border-radius: 6px; border: 1px solid #333; }
.screenshot-label { display: block; color: #8892b0; font-size: 0.75rem; margin-top: 0.25rem; }
.screenshot.missing { color: #e63946; font-style: italic; }
.empty { color: #8892b0; font-style: italic; padding: 2rem; text-align: center; }
footer {
  text-align: center; padding: 2rem; color: #555; font-size: 0.85rem;
  border-top: 1px solid #0f3460; margin-top: 2rem;
}
footer strong { color: #53d8fb; }
@media (max-width: 768px) {
  .step-data { grid-template-columns: 1fr; }
  .info-grid { grid-template-columns: 1fr 1fr; }
  .summary-grid { grid-template-columns: 1fr 1fr; }
}
"#;

// ---------------------------------------------------------------------------
// Embedded JavaScript
// ---------------------------------------------------------------------------

const JS: &str = r#"
function toggleStep(header) {
  header.classList.toggle('open');
  const body = header.nextElementSibling;
  body.style.display = body.style.display === 'none' ? 'block' : 'none';
}
document.addEventListener('keydown', function(e) {
  if (e.key === 'a' && !e.ctrlKey && !e.metaKey) {
    document.querySelectorAll('.step-header').forEach(h => {
      if (!h.classList.contains('open')) h.click();
    });
  }
  if (e.key === 'c' && !e.ctrlKey && !e.metaKey) {
    document.querySelectorAll('.step-header.open').forEach(h => h.click());
  }
});
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::trace::recorder::{
        AssertionSummary, TraceData, TraceDevice, TraceStep, TraceSummary,
    };
    use serde_json::json;

    fn sample_trace() -> TraceData {
        let mut trace = TraceData::new("test-report");
        trace.trace_id = "test-report-20260324-140000".to_string();
        trace.started_at = "2026-03-24T14:00:00Z".to_string();
        trace.ended_at = Some("2026-03-24T14:05:00Z".to_string());
        trace.device = Some(TraceDevice {
            udid: "ABC-123".to_string(),
            name: "iPhone 16 Pro".to_string(),
            runtime: Some("iOS 26.0".to_string()),
            scale: Some(3),
        });
        trace.steps.push(TraceStep {
            seq: 1,
            timestamp: "2026-03-24T14:00:01Z".to_string(),
            action: "tap".to_string(),
            input: json!({"ref": 5}),
            output: json!({"tapped": true}),
            duration_ms: 300,
            screenshot_before: None,
            screenshot_after: None,
        });
        trace.steps.push(TraceStep {
            seq: 2,
            timestamp: "2026-03-24T14:00:02Z".to_string(),
            action: "assert".to_string(),
            input: json!({"visible": ["Login"]}),
            output: json!({"pass": true}),
            duration_ms: 150,
            screenshot_before: None,
            screenshot_after: None,
        });
        trace.summary = Some(TraceSummary {
            total_steps: 2,
            total_duration_ms: 450,
            assertions: AssertionSummary {
                total: 1,
                passed: 1,
                failed: 0,
            },
            retries: 0,
        });
        trace
    }

    #[test]
    fn test_render_html_contains_trace_name() {
        let trace = sample_trace();
        let html = render_html(&trace);
        assert!(html.contains("test-report"));
        assert!(html.contains("test-report-20260324-140000"));
    }

    #[test]
    fn test_render_html_contains_device_info() {
        let trace = sample_trace();
        let html = render_html(&trace);
        assert!(html.contains("iPhone 16 Pro"));
        assert!(html.contains("ABC-123"));
        assert!(html.contains("iOS 26.0"));
    }

    #[test]
    fn test_render_html_contains_steps() {
        let trace = sample_trace();
        let html = render_html(&trace);
        assert!(html.contains("#1"));
        assert!(html.contains("#2"));
        assert!(html.contains("action-tap"));
        assert!(html.contains("action-assert-pass"));
    }

    #[test]
    fn test_render_html_contains_summary() {
        let trace = sample_trace();
        let html = render_html(&trace);
        assert!(html.contains("Total Steps"));
        assert!(html.contains("450ms"));
        assert!(html.contains("1/1"));
    }

    #[test]
    fn test_render_html_status_completed() {
        let trace = sample_trace();
        let html = render_html(&trace);
        assert!(html.contains("Completed"));
        assert!(html.contains("completed"));
    }

    #[test]
    fn test_render_html_status_in_progress() {
        let mut trace = sample_trace();
        trace.ended_at = None;
        let html = render_html(&trace);
        assert!(html.contains("In Progress"));
        assert!(html.contains("in-progress"));
    }

    #[test]
    fn test_render_html_empty_steps() {
        let mut trace = TraceData::new("empty");
        trace.trace_id = "empty-test".to_string();
        let html = render_html(&trace);
        assert!(html.contains("No steps recorded"));
    }

    #[test]
    fn test_html_escape() {
        assert_eq!(html_escape("<script>"), "&lt;script&gt;");
        assert_eq!(html_escape("a & b"), "a &amp; b");
        assert_eq!(html_escape("\"hello\""), "&quot;hello&quot;");
    }

    #[test]
    fn test_format_duration() {
        assert_eq!(format_duration(500), "500ms");
        assert_eq!(format_duration(1500), "1.5s");
        assert_eq!(format_duration(65000), "1m 5s");
    }

    #[test]
    fn test_render_html_is_valid_structure() {
        let trace = sample_trace();
        let html = render_html(&trace);
        assert!(html.starts_with("<!DOCTYPE html>"));
        assert!(html.contains("</html>"));
        assert!(html.contains("<style>"));
        assert!(html.contains("<script>"));
    }
}
